### ISSUE TITLE
JPA Entity 매핑

### ISSUE THREAD

**Issue by Capoomaru** [YU-RentCar/YURentCar-be#1]
## 💡 어떤 기능을 구현하나요?
ERD 설계에 따라 JPA 엔티티를 매핑합니다.

### User
- [x] User
- [x] Admin
### Reservation
- [x] Reservation
- [x] Card
- [x] Point
- [x] Pay
- [x] Review
### Car
- [x] Car
- [x] CarSpecification
- [x] Key
- [x] BranchCar
### Branch
- [x] Branch
- [x] KeyStorage
- [x] Kiosk
- [x] ParkingSpot
- [x] Notice
### Insurance
- [x] InsuranceCompany
- [x] InsuranceContract
- [x] BranchInsuranceCompanyContraction

# 💡 Refactoring
- [ ] #31

**Comment by Capoomaru** [comment]
기초적인 Entity 관련 구축 완료

**Comment by Capoomaru** [comment]
# 🔥 Issue
* Branch-branchAddress
   * postgres에서 point 타입에 대한 비공식 지원으로 인해 JPA 연동이 불가능에 가까움
   * 위도, 경도로 수정

**Comment by Ghanadara** [comment]
처리 완료
